import { expect, test } from '@playwright/test'

test('pílula abre pelo teclado, fecha com Escape e devolve o foco', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'Abrir menu' })
  const nav = page.getByRole('navigation', { name: 'Navegação principal' })
  await expect(nav).toHaveCount(0)
  await expect(page.locator('#site-menu')).toHaveAttribute('inert', '')
  await trigger.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Fechar menu' })).toHaveAttribute('aria-expanded', 'true')
  await expect(nav).toBeVisible()
  await page.keyboard.press('Tab')
  const projects = nav.getByRole('link', { name: 'Projetos', exact: true })
  await expect(projects).toBeFocused()
  await expect(projects).toHaveCSS('outline-style', 'solid')
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  await expect(nav).toHaveCount(0)
  await expect(page.locator('#site-menu')).toHaveCSS('height', '0px')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Ver projeto Disk', exact: true })).toBeFocused()
})

test('menu navega para a seção, fecha e mantém o destino abaixo da pílula', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Abrir menu' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('link', { name: 'Sobre mim', exact: true }).click()
  await expect(page).toHaveURL(/#sobre$/)
  await expect(page.locator('#sobre')).toBeFocused()
  await expect(page.getByRole('button', { name: 'Abrir menu' })).toHaveAttribute('aria-expanded', 'false')
  await expect.poll(async () => {
    const target = await page.locator('#sobre').boundingBox()
    const header = await page.locator('.header-pill').boundingBox()
    return Boolean(target && header && target.y >= header.y + header.height)
  }).toBe(true)
  await page.getByRole('button', { name: 'Abrir menu' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('link', { name: 'Modelos', exact: true }).click()
  await expect(page).toHaveURL(/\/modelos$/)
  await page.getByRole('button', { name: 'Abrir menu' }).click()
  await expect(page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('link', { name: 'Modelos', exact: true })).toHaveAttribute('aria-current', 'page')
})

test('clique fora e saída do foco fecham o menu sem prender a navegação', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Abrir menu' }).click()
  await page.mouse.click(4, 180)
  await expect(page.getByRole('button', { name: 'Abrir menu' })).toHaveAttribute('aria-expanded', 'false')
  await page.getByRole('button', { name: 'Abrir menu' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('link', { name: 'Contato', exact: true }).focus()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Ver projeto Disk', exact: true })).toBeFocused()
  await expect(page.getByRole('button', { name: 'Abrir menu' })).toHaveAttribute('aria-expanded', 'false')
})

test('animação tolera cliques rápidos e mudança para movimento reduzido', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-boot', 'ready')
  const trigger = page.locator('.menu-trigger')
  await trigger.click()
  await expect.poll(() => page.locator('#site-menu').evaluate(el => el.getBoundingClientRect().height)).toBeGreaterThan(20)
  for (let i = 0; i < 4; i++) await trigger.dispatchEvent('click')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('.pill-menu-link').last()).toHaveCSS('opacity', '1')
  await trigger.click()
  await expect(page.locator('#site-menu')).toHaveCSS('height', '0px')
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('menu aberto se adapta a telas baixas e troca de tema', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'light' })
  await page.goto('/')
  await page.getByRole('button', { name: 'Abrir menu' }).click()
  await page.getByRole('button', { name: 'Tema escuro', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('button', { name: 'Fechar menu' })).toHaveAttribute('aria-expanded', 'true')
  await page.setViewportSize({ width: 568, height: 320 })
  const contact = page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('link', { name: 'Contato', exact: true })
  await contact.focus()
  await expect(contact).toBeInViewport()
  const bounds = await page.locator('.header-pill').boundingBox()
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(320)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/#contato$/)
  await expect(page.locator('#contato')).toBeFocused()
})
