import { expect, test } from '@playwright/test'

test('mouse dá profundidade ao produto sem deslocar a área de clique', async ({ page, isMobile }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-boot', 'ready')
  await expect(page.locator('.product-card').first()).toHaveCSS('opacity', '1')
  const card = page.getByRole('link', { name: 'Ver projeto Disk', exact: true })
  const art = card.locator('.product-art > span')
  await card.scrollIntoViewIfNeeded()
  const before = await card.boundingBox()
  if (!before) throw new Error('Card não está visível')
  await page.mouse.move(before.x + before.width * 0.8, before.y + before.height * 0.3)
  if (isMobile) {
    await expect(card).not.toHaveAttribute('data-pointer-active')
    await expect(art).not.toHaveAttribute('style')
    await card.tap()
  } else {
    await expect(card).toHaveAttribute('data-pointer-active', 'true')
    await expect.poll(() => art.evaluate(el => new DOMMatrixReadOnly(getComputedStyle(el).transform).m41)).toBeGreaterThan(4)
    await expect.poll(() => card.evaluate(el => Number(getComputedStyle(el, '::before').opacity))).toBeGreaterThan(0.9)
    const right = await art.getAttribute('style')
    await page.mouse.move(before.x + before.width * 0.2, before.y + before.height * 0.7)
    await expect.poll(() => art.evaluate(el => new DOMMatrixReadOnly(getComputedStyle(el).transform).m41)).toBeLessThan(-4)
    expect(await art.getAttribute('style')).not.toBe(right)
    expect(await card.boundingBox()).toEqual(before)
    await page.mouse.move(0, 0)
    await expect(card).not.toHaveAttribute('data-pointer-active')
    await expect.poll(() => art.evaluate(el => Math.abs(new DOMMatrixReadOnly(getComputedStyle(el).transform).m41))).toBeLessThan(0.05)
    await expect.poll(() => card.evaluate(el => Number(getComputedStyle(el, '::before').opacity))).toBeLessThan(0.01)
    await card.click()
  }
  await expect(page).toHaveURL(/\/projetos\/disk$/)
  await expect(page.getByRole('heading', { level: 1, name: 'Disk', exact: true })).toBeVisible()
})

test('preferência de movimento remove os efeitos e permite reativá-los', async ({ page, isMobile }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/projetos/disk')
  await expect(page.locator('html')).toHaveAttribute('data-boot', 'ready')
  const cover = page.locator('.project-cover .product-visual')
  const art = cover.locator('.product-art > span')
  await cover.hover({ position: { x: 70, y: 70 } })
  if (!isMobile) await expect(cover).toHaveAttribute('data-pointer-active', 'true')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(cover).not.toHaveAttribute('data-pointer-active')
  await expect.poll(() => art.evaluate(el => el.getAttribute('style') || '')).toBe('')
  expect(await cover.evaluate(el => getComputedStyle(el, '::before').display)).toBe('none')
  await page.mouse.move(150, 150)
  await expect(cover).not.toHaveAttribute('data-pointer-active')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await cover.hover({ position: { x: 100, y: 90 } })
  if (!isMobile) await expect(cover).toHaveAttribute('data-pointer-active', 'true')
  else await expect(cover).not.toHaveAttribute('data-pointer-active')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('ícones respondem ao mouse e o teclado mantém foco e navegação', async ({ page, isMobile }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference', colorScheme: 'dark' })
  await page.goto('/modelos')
  await expect(page.locator('html')).toHaveAttribute('data-boot', 'ready')
  const footer = page.getByRole('contentinfo')
  const link = footer.getByRole('link', { name: 'GitHub', exact: true })
  await link.scrollIntoViewIfNeeded()
  // Flush the scroll event before starting a new pointer interaction.
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  const before = await link.boundingBox()
  if (!before) throw new Error('Link não está visível')
  await page.mouse.move(before.x + before.width * 0.8, before.y + before.height * 0.5)
  if (!isMobile) {
    await expect(link).toHaveAttribute('data-pointer-active', 'true')
    await expect.poll(() => link.locator('svg').evaluate(el => new DOMMatrixReadOnly(getComputedStyle(el).transform).m41)).toBeGreaterThan(2)
    expect(await link.boundingBox()).toEqual(before)
  }
  await footer.getByRole('link', { name: 'João Sousa, início' }).focus()
  await page.keyboard.press('Tab')
  await expect(link).toBeFocused()
  await expect(link).not.toHaveAttribute('data-pointer-active')
  expect(await link.evaluate(el => getComputedStyle(el).outlineStyle)).toBe('solid')
  await page.keyboard.press('Tab')
  await expect(footer.getByRole('link', { name: 'LinkedIn', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(footer.getByRole('link', { name: 'WhatsApp profissional' })).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('símbolos do hero acompanham o mouse e descansam ao perder foco', async ({ page, isMobile }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-boot', 'ready')
  const hero = page.locator('.hero')
  const motif = page.locator('.hero-motif').first()
  const heading = page.getByRole('heading', { name: 'Software, tempo real e IA.' })
  await expect.poll(() => heading.locator('.hero-line > span').first().evaluate(el => Math.abs(new DOMMatrixReadOnly(getComputedStyle(el).transform).m42))).toBeLessThan(0.01)
  const before = await heading.boundingBox()
  await hero.hover({ position: { x: 80, y: 180 } })
  if (!isMobile) {
    await expect(hero).toHaveAttribute('data-pointer-active', 'true')
    await expect.poll(() => motif.evaluate(el => new DOMMatrixReadOnly(getComputedStyle(el).transform).m41)).toBeLessThan(-3)
    expect(await heading.boundingBox()).toEqual(before)
    await page.evaluate(() => window.dispatchEvent(new Event('blur')))
    await expect(hero).not.toHaveAttribute('data-pointer-active')
    await expect.poll(() => motif.evaluate(el => Math.abs(new DOMMatrixReadOnly(getComputedStyle(el).transform).m41))).toBeLessThan(0.05)
  } else {
    await expect(motif).not.toHaveAttribute('style')
  }
})
