import { expect, test } from '@playwright/test'

test.use({ colorScheme: 'light' })

test('a luz apaga e acende por teclado, preservando foco e preferência', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  const toggle = page.getByRole('button', { name: 'Tema escuro', exact: true })
  await toggle.focus()
  await page.keyboard.press('Enter')
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await expect(toggle).toHaveAttribute('aria-disabled', 'false')
  await expect(toggle).toBeFocused()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('html')).toHaveCSS('background-color', 'rgb(20, 25, 35)')
  await expect(page.locator('meta[name="theme-color"]')).toHaveAttribute('content', '#141923')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.reload()
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await toggle.focus()
  await page.keyboard.press('Space')
  await expect(toggle).toHaveAttribute('aria-pressed', 'false')
  await expect(toggle).toHaveAttribute('aria-disabled', 'false')
  await expect(toggle).toBeFocused()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  expect(errors).toEqual([])
})

test('acompanha o sistema até uma escolha explícita', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await page.goto('/')
  const toggle = page.getByRole('button', { name: 'Tema escuro', exact: true })
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(toggle).toHaveAttribute('aria-pressed', 'false')
  await toggle.click()
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
})

test('transição cobre a tela e termina mesmo com cliques repetidos', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  const toggle = page.getByRole('button', { name: 'Tema escuro', exact: true })
  await toggle.click()
  await expect.poll(() => page.evaluate(() => document.getAnimations().some(animation => {
    const effect = animation.effect as KeyframeEffect
    return effect.pseudoElement === '::view-transition-old(root)' &&
      effect.getKeyframes().some(frame => typeof frame.clipPath === 'string')
  }))).toBe(true)
  await toggle.dispatchEvent('click')
  await expect(toggle).toHaveAttribute('aria-disabled', 'false')
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('html')).not.toHaveAttribute('data-theme-transition')
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-pressed', 'false')
  await expect(toggle).toHaveAttribute('aria-disabled', 'false')
})

test('movimento reduzido e ausência da API mantêm a troca funcional', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const toggle = page.getByRole('button', { name: 'Tema escuro', exact: true })
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('html')).not.toHaveAttribute('data-theme-transition')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.evaluate(() => { Object.defineProperty(document, 'startViewTransition', { value: undefined }) })
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('html')).not.toHaveAttribute('data-theme-transition')
})

test('armazenamento bloqueado não impede o tema', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(window, 'localStorage', { get() { throw new Error('Storage blocked') } })
  })
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await page.goto('/')
  const toggle = page.getByRole('button', { name: 'Tema escuro', exact: true })
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-pressed', 'false')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('ativar movimento reduzido durante a transição libera o botão', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  const toggle = page.getByRole('button', { name: 'Tema escuro', exact: true })
  await toggle.click()
  await expect(page.locator('html')).toHaveAttribute('data-theme-transition', 'dark')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(toggle).toHaveAttribute('aria-disabled', 'false')
  await expect(page.locator('html')).not.toHaveAttribute('data-theme-transition')
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-pressed', 'false')
})
